In [103]:
import numpy as np


In [104]:
x = np.array([[1, 2, 3], [4,5,6]])

x

array([[1, 2, 3],
       [4, 5, 6]])

In [105]:
a = np.transpose([[7,8]])

y = np.hstack((x,a))

y

array([[1, 2, 3, 7],
       [4, 5, 6, 8]])

In [106]:
b = np.array([10,11,12,13])

z = np.vstack((y,b))

z

array([[ 1,  2,  3,  7],
       [ 4,  5,  6,  8],
       [10, 11, 12, 13]])

In [107]:
m = np.array([1, 2, 3])


In [108]:
np.append(m, 5)

array([1, 2, 3, 5])

In [109]:
class Tree(object):
    def __init__(self, value='root', children=None):
        self.value = value
        self.children = []
        if children is not None:
            for child in children:
                self.add_child(child)
  
    def add_child(self, node):
        assert isinstance(node, Tree)
        self.children.append(node)

In [110]:
t = Tree('*', [Tree('1'),
               Tree('2'),
               Tree('+', [Tree('3'),
                          Tree('4')])])

In [111]:
t.value


'*'